import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync(new URL("../app.html", import.meta.url), "utf8");
const app = readFileSync(new URL("../app.js", import.meta.url), "utf8");

test("notes are edited independently from loan terms", () => {
  const loanForm = html.match(/<form id="loan-form-modal">([\s\S]*?)<\/form>/)?.[1] || "";
  assert.doesNotMatch(loanForm, /loanNotes|loan-note-text/);
  assert.match(html, /id="loan-note-form"/);
  assert.match(html, /id="loan-note-text"/);
  assert.match(app, /const LoanNoteHandler/);
});

test("generic modal close controls restore page scrolling", () => {
  assert.match(app, /else UIHandler\.closeModal\(modal\.id\);/);
});

test("secondary application actions live in the main overflow menu", () => {
  assert.match(html, /id="main-actions-menu-btn"/);
  assert.match(html, /data-main-action="settings"/);
  assert.match(html, /data-main-action="combine"/);
  assert.match(html, /data-main-action="data-management"/);
  assert.doesNotMatch(html, /id="combine-loans-btn"/);
  assert.doesNotMatch(html, /id="profile-settings"/);
});

test("combined-loan rendering relies on loan-part cards and retains loan notes", () => {
  assert.doesNotMatch(app, /const combinedOverviewCard/);
  assert.match(app, /loan-notes-card/);
  assert.match(app, /part\.note/);
});

test("combining requires a custom title and accepts separate optional facility notes", () => {
  assert.match(html, /id="combine-loan-name"[^>]*required/);
  assert.match(html, /id="combine-loan-notes"/);
  assert.doesNotMatch(app, /dataset\.autogenerated/);
  assert.match(app, /combineLoans\(selected, \{ id: crypto\.randomUUID\(\), name, notes \}\)/);
});
