import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync(new URL("../app.html", import.meta.url), "utf8");
const app = readFileSync(new URL("../app.js", import.meta.url), "utf8");

test("loan editing exposes a separate optional notes field", () => {
  assert.match(html, /id="loanNotes"/);
  assert.match(html, /data-translate="loanNotes"/);
  assert.match(app, /querySelector\("#loanNotes"\)\.value/);
});

test("secondary application actions live in the main overflow menu", () => {
  assert.match(html, /id="main-actions-menu-btn"/);
  assert.match(html, /data-main-action="settings"/);
  assert.match(html, /data-main-action="combine"/);
  assert.match(html, /data-main-action="data-management"/);
  assert.doesNotMatch(html, /id="combine-loans-btn"/);
  assert.doesNotMatch(html, /id="profile-settings"/);
});

test("combined-loan rendering includes original amounts and loan notes", () => {
  assert.match(app, /sourceOriginalAmount/);
  assert.match(app, /loan-notes-card/);
});

test("combining requires a custom title and accepts separate optional facility notes", () => {
  assert.match(html, /id="combine-loan-name"[^>]*required/);
  assert.match(html, /id="combine-loan-notes"/);
  assert.doesNotMatch(app, /dataset\.autogenerated/);
  assert.match(app, /combineLoans\(selected, \{ id: crypto\.randomUUID\(\), name, notes \}\)/);
});